export const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
export const GET_RESTORANT_BY_ID = "GET_RESTORANT_BY_ID";
export const GET_RESTORANT_BY_STRING = "GET_RESTORANT_BY_STRING";

export const FILTER_CARDS = "FILTER_CARDS";
export const ORDER_CARDS = "ORDER_CARDS";

export const CLEAR_STATE_RESTORANT_BY_ID = "CLEAR_STATE_RESTORANT_BY_ID";
export const CLEAR_STATE_RESTORANT_BY_STRING = "CLEAR_STATE_RESTORANT_BY_STRING";
export const CLEAR_SEARCH_TEXT = "CLEAR_SEARCH_TEXT";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

export const GET_LINK_MERCADOPAGO = "GET_LINK_MERCADOPAGO";
export const CLEAR_LINK_MERCADOPAGO = "CLEAR_LINK_MERCADOPAGO";


export const GET_TYPES_FOODS = "GET_TYPES_FOODS";
export const GET_ATMOSPHERE = "GET_ATMOSPHERE";
export const GET_SECTIONS = "GET_SECTIONS";
export const GET_DIET = "GET_DIET";
export const GET_EXTRA = "GET_EXTRA";

export const FILTER_RESTORANTS = "FILTER_RESTORANTS";
