export const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
export const GET_RESTORANT_BY_ID = "GET_RESTORANT_BY_ID";
export const GET_RESTORANT_BY_STRING = "GET_RESTORANT_BY_STRING";

export const FILTER_CARDS = "FILTER_CARDS";
export const ORDER_CARDS = "ORDER_CARDS";

export const CLEAR_STATE_RESTORANT_BY_ID = "CLEAR_STATE_RESTORANT_BY_ID";
export const CLEAR_STATE_RESTORANT_BY_STRING = "CLEAR_STATE_RESTORANT_BY_STRING";
export const CLEAR_SEARCH_TEXT = "CLEAR_SEARCH_TEXT";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";



export const GET_TYPES_FOODS = "GET_TYPES_FOODS";
export const GET_ATMOSPHERE = "GET_ATMOSPHERE";
export const GET_SECTIONS = "GET_SECTIONS";
export const GET_HAS_WITH = "GET_HAS_WITH";
export const GET_OTHERS = "GET_OTHERS";
