const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
const FILTER_CARDS = "FILTER_CARDS";
const ORDER_CARDS = "ORDER_CARDS";


module.exports = {
    GET_ALL_RESTORANTS,
    FILTER_CARDS,
    ORDER_CARDS,
}