const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
const GET_RESTORANT_BY_ID = "GET_RESTORANT_BY_ID";
const GET_RESTORANT_BY_STRING = "GET_RESTORANT_BY_STRING";

const FILTER_CARDS = "FILTER_CARDS";
const ORDER_CARDS = "ORDER_CARDS";

const CLEAR_STATE_RESTORANT_BY_ID = "CLEAR_STATE_RESTORANT_BY_ID";

module.exports = {
    GET_ALL_RESTORANTS,
    GET_RESTORANT_BY_ID,
    GET_RESTORANT_BY_STRING,

    FILTER_CARDS,
    ORDER_CARDS,

    CLEAR_STATE_RESTORANT_BY_ID,
}