/* detailRestaurant: {
    _id: "",
    name: "",
    address: {
      streetName: "",
      streetNumber: 0,
      neighborhood: "",
      city: "",
      state: "",
      country: "",
    },
    images: [],
    contact: {
      phoneNumber: "",
      email: "",
      socialMedia: { instagram: "", facebook: "", wpp: "" },
    },
    tables: 41,
    schedule: [
      {
        monday: { open: "", close: "" },
        tuesday: { open: "", close: "" },
        wednesday: { open: "", close: "" },
        thursday: { open: "", close: "" },
        friday: { open: "", close: "" },
        saturday: { open: "", close: "" },
        sunday: { open: "", close: "" },
      },
    ],
    menu: [
      "italiana",
      "asiática",
      "internacional",
      "hamburguesas",
      "alta cocina",
      "bares",
      "pizzerías",
      "mediterránea",
      "gourmet",
    ],
    diets: ["vegano", "celiaco", "vegetariano"],
    paymentMethods: [
      "credito",
      "debito",
      "mercadopago",
      "efectivo",
      "transferencia",
    ],
    atmosphere: ["musica en vivo", "familiar", "romantico", "formal"],
    extras: ["petfriendly", "bar", "wi-fi", "fumadores", "menú para niño"],
    section: ["terraza", "barra", "salón principal"],
    ranking: "",
    active: true,
  }, */
